name: rolex_stands_finding
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome: ^5.10.1
  google_fonts: ^3.0.1
  get: ^4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  flutter_otp_text_field: ^1.1.1
  line_awesome_flutter: ^2.0.0
  url_launcher: ^6.1.10
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  location: ^4.3.0
  shared_preferences: ^2.0.13
  flutter_dotenv: ^5.0.2
  mapbox_gl: ^0.15.0
  dio: ^4.0.6
  cached_network_image: ^3.2.0
  lottie: ^2.2.0
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icond.png"

flutter_native_splash:

  color: "#FFFFFF"
  image: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/login_signup_images/
    - assets/icon/
    - assets/config/.env
    - assets/location.json
