// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiT2FkJQH0inqtdYkAZF4AzVaDWIGwydg',
    appId: '1:571105515916:android:0881df9f39ee1b733bdea9',
    messagingSenderId: '571105515916',
    projectId: 'flutter-login-app-7bd8a',
    storageBucket: 'flutter-login-app-7bd8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0wpw-QgrtTC28xRzPdtZjKs52JRcLw00',
    appId: '1:571105515916:ios:d0863d8ad690e61b3bdea9',
    messagingSenderId: '571105515916',
    projectId: 'flutter-login-app-7bd8a',
    storageBucket: 'flutter-login-app-7bd8a.appspot.com',
    androidClientId: '571105515916-8oalcsvd547cjv3oph7kfbfl0igbegh2.apps.googleusercontent.com',
    iosClientId: '571105515916-jbh81845hfv68en1vck2hqmtal3a2ucr.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolexStandsFinding',
  );
}
